# Numpy Questions to make you (9/10 rated)

In [1]:
import numpy as np

In [2]:
# Create a NumPy array containing numbers from 1 to 10.

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
#Create an array containing all even numbers from 2 to 20.
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


In [5]:
# Create a 3×3 array filled with zeros.
arr = np.zeros((3,3),dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
# Create a 4×4 array filled with ones.
arr = np.ones((4,4),dtype=int) 
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [19]:
# Create a 5×5 identity matrix. 
arr = np.identity((5),dtype=int)
print(arr)
brr = np.eye(5,dtype=int)
print(brr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [9]:
# Create an array containing 10 equally spaced values between 0 and 100. 
arr = np.linspace(0,100,10)
print(arr)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [12]:
# Find the shape, size, and dimension of the following array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)

(2, 3)
6
2


In [14]:
# Convert the following Python list into a NumPy array: 
lst = [10, 20, 30, 40, 50] 
arr = np.array(lst) 
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [15]:
# Create a 2×3 array using numbers from 1 to 6. 
arr = np.arange(1,7).reshape(2,3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [23]:
# Create a 3×4 random integer array containing values between 1 and 50.
arr = np.random.randint(1,51,(3,4))
print(arr)

[[36 33 22 26]
 [49  3 21 13]
 [34  8 49 20]]


In [24]:
# Extract the third element from the following array:
arr = np.array([5, 10, 15, 20, 25]) 
print(arr[2])

15


In [25]:
# Extract the last three elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:])

[5 6 7]


In [28]:
# Extract the second row:
arr = np.array([[10, 20], [30, 40], [50, 60]])
print(arr[1])

[30 40]


In [29]:
# Extract the first column: 
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(arr[:,0])

[1 4 7]


In [31]:
# Reverse the following array: 
arr = np.array([1, 2, 3, 4, 5]) 
rev_arr = arr[::-1]
print(rev_arr)
print(type(rev_arr))

[5 4 3 2 1]
<class 'numpy.ndarray'>


In [146]:
# Extract all even numbers:
arr = np.array([12, 15, 18, 21, 24, 27, 30])
print(arr[arr%2==0])

[12 18 24 30]


In [147]:
# Replace all values greater than 50 with 0:
arr = np.array([20, 40, 60, 80, 100])
arr[arr>50] = 0
print(arr)

[20 40  0  0  0]


In [38]:
# Extract the diagonal elements:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
drr = np.diag(arr)
print(drr)

[1 5 9]


In [39]:
# Select all elements greater than 10:
arr = np.array([5, 10, 15, 20, 25]) 
brr = arr[arr>10]
print(brr)

[15 20 25]


In [40]:
# Replace all odd numbers with -1: 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8]) 
arr[arr%2==1] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8]


In [53]:
# Find the sum of all elements: 
arr = np.array([10, 20, 30, 40, 50]) 
print(np.median(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))

150
30.0
14.142135623730951
10
50
30.0
30.0
14.142135623730951
150
10
50


In [54]:
# Add the following arrays. 
a = np.array([1, 2, 3])

b = np.array([4, 5, 6]) 
c = a + b
print(c)

[5 7 9]


In [55]:
# Multiply the following arrays element-wise:
a = np.array([2, 4, 6])

b = np.array([1, 3, 5]) 
c = a*b
print(c)

[ 2 12 30]


In [58]:
# Find the square of each element:
arr = np.array([2, 4, 6, 8]) 
brr = arr**2
print(brr)
print(np.square(arr))

[ 4 16 36 64]
[ 4 16 36 64]


In [57]:
# Find the square root of each element: 
arr = np.array([4, 9, 16, 25]) 
print(np.sqrt(arr))

[2. 3. 4. 5.]


In [59]:
# Normalize the following array: 
arr = np.array([10, 20, 30, 40, 50]) 
normalized = (arr - arr.min())/(arr.max() - arr.min())
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [61]:
# Reshape the following array into a 3×4 matrix: 
arr = np.arange(1, 13) 
brr = arr.reshape(3,4)
brr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
# Flatten the following array: 
arr = np.array([[1, 2], [3, 4], [5, 6]]) 
brr = arr.flatten()
brr

array([1, 2, 3, 4, 5, 6])

In [71]:
# Transpose the following matrix: 
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)
print(np.transpose(arr)) 

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [72]:
# Vertically stack the following arrays: 
a = np.array([1, 2, 3])

b = np.array([4, 5, 6]) 
c =  np.vstack((a,b))
print(c)

[[1 2 3]
 [4 5 6]]


In [73]:
# Horizontally stack the arrays.
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])  

c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6]


In [74]:
# Split the array into three equal parts.

arr = np.arange(1,10)
parts = np.split(arr,3)
print(parts)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [76]:
# Reshape the array into a 2×2×2 array. 
arr = np.arange(1,9).reshape(2,2,2) 
print(arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [79]:
# Create a copy of the array. 
arr = np.arange(10,31,10)
copy_arr = arr.copy()
copy_arr[0] = 100
print(copy_arr)
print(arr)

[100  20  30]
[10 20 30]


In [83]:
# Create a view of the array.
arr = np.array([10, 20, 30])
view_arr = arr.view()
view_arr[0] = 66
print(view_arr)
print(type(arr))
print(arr)

[66 20 30]
<class 'numpy.ndarray'>
[66 20 30]


In [84]:
# Check whether the copy and the view share memory with the original array.a

arr = np.arange(1,5)
copy_arr = arr.copy()
view_arr = arr.view()
arr[0] = 100
print(arr)
print(view_arr)
print(copy_arr)

[100   2   3   4]
[100   2   3   4]
[1 2 3 4]


In [85]:
data = np.array([
    [80, 75, 90],
    [85, 88, 92],
    [78, 80, 85],
    [90, 95, 98]
]) 

In [86]:
# Find the average marks in each subject: 
avg_arr = np.mean(data,axis = 0)
print(avg_arr)

[83.25 84.5  91.25]


In [87]:
#  Find the average marks of each student.
student_avg = np.mean(data,axis=1)
print(student_avg)

[81.66666667 88.33333333 81.         94.33333333]


In [90]:
# Find the student with the highest total marks.
total_marks = np.sum(data,axis=1)
print(total_marks)
highest = np.argmax(total_marks)
print(highest+1)

[245 265 243 283]
4


In [91]:
# Count how many students scored more than 85 in the third subject. 
count = np.sum(data[:,2]>85)
print(count)

3


In [92]:
# Find the maximum marks in each subject. 
maximum = np.max(data,axis=0)
print(maximum)

[90 95 98]


In [93]:
# Find the minimum marks in each subject.
minimum = np.min(data,axis=0)
print(minimum)

[78 75 85]


In [96]:
# Find students whose average marks are greater than 85.
avg_marks = np.mean(data,axis = 1)
students = data[avg_marks>85]
print(students)

[[85 88 92]
 [90 95 98]]


In [97]:
# Replace all marks below 80 with 0.
new_data = data.copy()
new_data[new_data<80] = 0
print(new_data)

[[80  0 90]
 [85 88 92]
 [ 0 80 85]
 [90 95 98]]


In [98]:
# Count how many values are greater than the overall mean.
overall_mean = np.mean(data)
count = np.sum(data > overall_mean)
print(count)

6


In [99]:
# Find the correlation matrix of the subjects. 
correlation = np.corrcoef(data.T)
print(correlation)

[[1.         0.92493891 0.96541787]
 [0.92493891 1.         0.7983313 ]
 [0.96541787 0.7983313  1.        ]]


In [100]:
# Broadcasting
arr = np.array([1,2,3,4])
arr = arr + 10
print(arr)

[11 12 13 14]


In [101]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
arr = arr*2
print(arr)

[[ 2  4  6]
 [ 8 10 12]]


In [102]:
# axis=0 vs axis=1
data = np.array([
    [80, 75, 90],
    [85, 88, 92],
    [78, 80, 85]
]) 
print(np.sum(data,axis=0)) # columnwise
print(np.sum(data,axis=1)) # rowwise

[243 243 267]
[245 265 243]


In [106]:
# np.where() 
arr = np.arange(10,51,10)
print(arr)
result = np.where(arr>30)
replace_arr = np.where(arr>30,100,arr)
print(replace_arr)
print(result)
print(arr)

[10 20 30 40 50]
[ 10  20  30 100 100]
(array([3, 4]),)
[10 20 30 40 50]


In [107]:
# (unique(), sort(), argsort(), argmax()) 
arr = np.array([1, 2, 2, 3, 4, 4, 5])
uniq_arr = np.unique(arr)
print(uniq_arr)

[1 2 3 4 5]


In [108]:
sorted_arr = np.sort(arr) 
print(sorted_arr)

[1 2 2 3 4 4 5]


In [109]:
# np.argsort() -> returns index after sorting 
arr = np.array([8, 3, 5, 1, 9]) 
print(np.argsort(arr))

[3 1 2 0 4]


In [110]:
arr = np.array([10, 50, 30, 80, 20]) 
print(np.argmax(arr))

3


In [111]:
print(np.argmin(arr))

0


In [113]:
# concatenate(), column_stack(), flatten(), ravel())
a = np.array([1, 2, 3])

b = np.array([4, 5, 6]) 

concat_arr = np.concatenate((a,b))
print(concat_arr)
print(np.column_stack((a,b)))

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [114]:
arr = np.array([[1, 2], [3, 4]]) 
flat_arr = arr.flatten()
print(flat_arr)

[1 2 3 4]


In [115]:
arr = np.array([[1, 2], [3, 4]])
r = arr.ravel()
arr[0,0] = 100
print(r)
print(arr)

[100   2   3   4]
[[100   2]
 [  3   4]]


In [123]:
 # Day 4 (Mini EDA)
data = np.array([
    [22, 85, 90],
    [19, 78, 88],
    [25, 92, 95],
    [18, 70, 75],
    [21, 88, 91]
]) 

In [117]:
# Extract the age column.
print(data[:,0])

[22 19 25 18 21]


In [118]:
# Find students younger than 21. 
arr = data[data[:,0]<21]
print(arr)

[[19 78 88]
 [18 70 75]]


In [135]:
# Find the average marks in each subject. 
data = np.array([
    [22, 85, 90],
    [19, 78, 88],
    [25, 92, 95],
    [18, 70, 75],
    [21, 88, 91]
]) 

avg_marks = np.mean(data, axis=0)

print(avg_marks)

[21.  82.6 87.8]


In [130]:
# Find the average age. 
avg_age = np.mean(data[:,0])
print(avg_age)

21.0


In [131]:
# Find students who scored more than 90 in the third column. 
print(data[data[:,2]>90])

[[25 92 95]
 [21 88 91]]


In [133]:
# Replace all marks below 80 with 0. 
data[data<80] = 0
print(data)

[[ 0 85 90]
 [ 0  0 88]
 [ 0 92 95]
 [ 0  0  0]
 [ 0 88 91]]


In [138]:
# Find the student with the highest total score. 
total_scores = np.sum(data[:,1:],axis=1)
print(total_scores)
highest_student = np.argmax(total_scores)
print(highest_student)
print(data[highest_student])

[175 166 187 145 179]
2
[25 92 95]


In [142]:
# Normalize the second column. 
new_data = data[:,2]
print(new_data)
normalized_arr = new_data - np.min(new_data)/np.max(new_data)-np.min(new_data)
print(normalized_arr)

[90 88 95 75 91]
[14.21052632 12.21052632 19.21052632 -0.78947368 15.21052632]


In [144]:
# Count how many values are greater than the overall mean. 
overall_mean = np.mean(data)
count = np.sum(data > overall_mean)
print(overall_mean)
print(count)

63.8
10


In [145]:
# Find the correlation matrix 
new_arr = data.T 
print(np.corrcoef(new_arr))

[[1.         0.91220832 0.82922151]
 [0.91220832 1.         0.94732406]
 [0.82922151 0.94732406 1.        ]]
