# NumPy — Complete Notes + 9/10 Difficulty Practice

> **Goal:** Build strong NumPy fundamentals for Data Science, ML and interviews.

NumPy (Numerical Python) provides fast, vectorized n-dimensional arrays and mathematical operations.

### Learning path
1. Arrays & attributes
2. Creation methods
3. Indexing & slicing
4. Boolean masking & `where`
5. Vectorization & broadcasting
6. Statistics
7. Reshaping & dimensions
8. Combining/splitting arrays
9. Copy vs view
10. Sorting/searching
11. Correlation
12. Mini EDA
13. Hard interview-style problems


## 1. Installation and import

```python
pip install numpy
```

```python
import numpy as np
```

### Why NumPy?
- Compact numerical data representation
- Vectorized operations (avoid Python loops)
- Broadcasting
- Linear algebra and statistics
- Foundation for pandas, scikit-learn and many ML libraries

**Core object:** `numpy.ndarray`


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


## 2. Creating arrays

### `arange(start, stop, step)`
`stop` is **exclusive**.

### `linspace(start, stop, num)`
Creates exactly `num` equally spaced values; endpoint is included by default.

### `zeros`, `ones`, `eye`, `identity`
Useful for initialization and matrix operations.


In [2]:
# 1 to 10
np.arange(1, 11)

# Even numbers 2 to 20
np.arange(2, 21, 2)

# 3x3 zeros
np.zeros((3, 3), dtype=int)

# 4x4 ones
np.ones((4, 4), dtype=int)

# 5x5 identity
np.eye(5, dtype=int)

# 10 equally spaced values from 0 to 100
np.linspace(0, 100, 10)


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## 3. Array attributes

For an array:
- `shape` → dimensions, e.g. `(2, 3)`
- `size` → total number of elements
- `ndim` → number of axes
- `dtype` → element data type
- `itemsize` → bytes occupied by one element

### Important distinction
A `(2, 3)` array has:
- `ndim = 2`
- `size = 6`


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("shape:", arr.shape)
print("size:", arr.size)
print("ndim:", arr.ndim)
print("dtype:", arr.dtype)
print("itemsize:", arr.itemsize)


shape: (2, 3)
size: 6
ndim: 2
dtype: int64
itemsize: 8


## 4. Reshaping

`reshape()` changes the shape **without changing the number of elements**.

Rule:

`old_size == new_shape_product`

Example: 12 elements → `(3, 4)` because `3 × 4 = 12`.

You can use `-1` to let NumPy infer one dimension.


In [4]:
arr = np.arange(1, 13)

print(arr.reshape(3, 4))
print(arr.reshape(2, 6))
print(arr.reshape(2, 2, 3))

# NumPy infers the second dimension
print(arr.reshape(3, -1))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 5. Indexing

Python uses **0-based indexing**.

For 2D array:
```text
arr[row, column]
```

Useful patterns:
- `arr[2]` → third row / third element in 1D
- `arr[:, 0]` → first column
- `arr[1:, 2:]` → rows from index 1 and columns from index 2


In [5]:
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

print("first row:", arr[0])
print("first column:", arr[:, 0])
print("third column:", arr[:, 2])
print("last two columns:", arr[:, 2:])
print("bottom-right block:", arr[1:, 2:])
print("element:", arr[0, 3])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
first row: [1 2 3 4]
first column: [1 5 9]
third column: [ 3  7 11]
last two columns: [[ 3  4]
 [ 7  8]
 [11 12]]
bottom-right block: [[ 7  8]
 [11 12]]
element: 4


## 6. Slicing

General syntax:

```python
arr[start:stop:step]
```

`stop` is exclusive.

For 2D:
```python
arr[row_start:row_stop, col_start:col_stop]
```

### Reverse
```python
arr[::-1]
```

### Important
Basic NumPy slicing often produces a **view**, not an independent copy. Mutating the slice can mutate the original array.


In [6]:
arr = np.arange(1, 13).reshape(3, 4)

print(arr[:, ::-1])       # reverse columns
print(arr[::-1, :])       # reverse rows
print(arr[::2, ::2])      # every second row/column
print(arr[0:2, 1:3])      # selected block


[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 1  3]
 [ 9 11]]
[[2 3]
 [6 7]]


## 7. Boolean masking

Boolean indexing is one of NumPy's most important Data Science features.

```python
arr[arr > 10]
arr[arr % 2 == 0]
```

For multiple conditions use:
- `&` → AND
- `|` → OR
- `~` → NOT

**Always parenthesize each condition.**


In [7]:
arr = np.arange(1, 11)

print(arr[arr > 5])
print(arr[arr % 2 == 0])
print(arr[(arr >= 3) & (arr <= 7)])
print(arr[(arr < 3) | (arr > 8)])
print(arr[~(arr % 2 == 0)])


[ 6  7  8  9 10]
[ 2  4  6  8 10]
[3 4 5 6 7]
[ 1  2  9 10]
[1 3 5 7 9]


## 8. Conditional replacement

### Direct masking
```python
arr[arr > 50] = 0
```

### `np.where(condition, value_if_true, value_if_false)`

Unlike direct assignment, `where` conveniently creates a result array.


In [8]:
arr = np.array([20, 40, 60, 80, 100])

arr2 = arr.copy()
arr2[arr2 > 50] = 0
print(arr2)

print(np.where(arr > 50, 100, arr))

idx = np.where(arr > 50)
print("indices:", idx)


[20 40  0  0  0]
[ 20  40 100 100 100]
indices: (array([2, 3, 4]),)


## 9. Vectorized arithmetic

NumPy performs operations element-wise.

```python
a + b
a - b
a * b
a / b
a ** 2
```

This is usually much faster and cleaner than explicit Python loops for numerical arrays.


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a % b)


## 10. Universal functions (ufuncs)

Common ufuncs:
- `np.sqrt`
- `np.exp`
- `np.log`
- `np.sin`
- `np.abs`
- `np.square`
- `np.power`

They operate element-wise.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))
print(np.square(arr))


## 11. Broadcasting

Broadcasting allows NumPy to perform operations between arrays of compatible shapes.

Example:
```text
[1, 2, 3, 4] + 10
```
adds 10 to every element.

### 2D + 1D example
A `(2, 3)` matrix can be added to a `(3,)` vector because the last dimensions match.

### Broadcasting rule
Compare dimensions from the **right**:
Two dimensions are compatible if:
1. they are equal, or
2. one of them is `1`, or
3. one dimension is missing.

Otherwise NumPy raises a broadcasting error.


In [9]:
arr = np.array([1, 2, 3, 4])
print(arr + 10)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
vector = np.array([10, 20, 30])

print(matrix + vector)


[11 12 13 14]
[[11 22 33]
 [14 25 36]]


## 12. Statistics

Core functions:
- `np.mean`
- `np.median`
- `np.std`
- `np.var`
- `np.sum`
- `np.min`
- `np.max`
- `np.argmax`
- `np.argmin`

### Standardization / Z-score

$$z = \frac{x - \mu}{\sigma}$$

After standardization, the values have approximately:
- mean = 0
- standard deviation = 1

### Min-Max normalization

$$x' = \frac{x-x_{min}}{x_{max}-x_{min}}$$

Result normally lies in `[0, 1]`.


In [10]:
data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
median = np.median(data)
std = np.std(data)
var = np.var(data)

z = (data - mean) / std
minmax = (data - data.min()) / (data.max() - data.min())

print(mean, median, std, var)
print("z-score:", z)
print("min-max:", minmax)


3.0 3.0 1.4142135623730951 2.0
z-score: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
min-max: [0.   0.25 0.5  0.75 1.  ]


## 13. `axis=0` vs `axis=1`

For a 2D matrix:

```text
axis=0 → collapse rows → operate column-wise
axis=1 → collapse columns → operate row-wise
```

For a `(3, 4)` matrix:
- `sum(axis=0)` → shape `(4,)`
- `sum(axis=1)` → shape `(3,)`

**Memory trick:** axis tells NumPy which dimension to collapse.


In [11]:
data = np.array([
    [80, 75, 90],
    [85, 88, 92],
    [78, 80, 85]
])

print("column sums:", np.sum(data, axis=0))
print("row sums:", np.sum(data, axis=1))
print("column means:", np.mean(data, axis=0))
print("row means:", np.mean(data, axis=1))


column sums: [243 243 267]
row sums: [245 265 243]
column means: [81. 81. 89.]
row means: [81.66666667 88.33333333 81.        ]


## 14. Matrix operations and transformations

### Transpose
`arr.T` or `np.transpose(arr)`

### Flatten
`flatten()` returns a **copy**.

### Ravel
`ravel()` tries to return a **view** when possible.

### Diagonal
`np.diag(matrix)` extracts the diagonal.


In [12]:
arr = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("transpose:\n", arr.T)
print("flatten:", arr.flatten())
print("ravel:", arr.ravel())

square = np.arange(1, 10).reshape(3, 3)
print("diagonal:", np.diag(square))


transpose:
 [[1 4]
 [2 5]
 [3 6]]
flatten: [1 2 3 4 5 6]
ravel: [1 2 3 4 5 6]
diagonal: [1 5 9]


## 15. Combining arrays

### `concatenate`
Joins arrays along an existing axis.

### `vstack`
Stacks vertically.

### `hstack`
Stacks horizontally.

### `column_stack`
Turns 1D arrays into columns and combines them.


In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("concatenate:", np.concatenate((a, b)))
print("vstack:\n", np.vstack((a, b)))
print("hstack:", np.hstack((a, b)))
print("column_stack:\n", np.column_stack((a, b)))


concatenate: [1 2 3 4 5 6]
vstack:
 [[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]
column_stack:
 [[1 4]
 [2 5]
 [3 6]]


## 16. Splitting arrays

`np.split(array, sections)` splits an array into equal sections.

For unequal splits, use `np.array_split`.



In [14]:
arr = np.arange(1, 10)

print(np.split(arr, 3))
print(np.array_split(arr, 4))


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


## 17. Copy vs View — very important

### Copy
```python
b = a.copy()
```
Independent memory. Changes to `b` do not affect `a`.

### View
```python
b = a.view()
```
Shares underlying data. Changes can affect `a`.

### Check memory sharing
```python
np.shares_memory(a, b)
```

This is a common interview question.


In [15]:
arr = np.arange(1, 5)

copy_arr = arr.copy()
view_arr = arr.view()

copy_arr[0] = 100
view_arr[1] = 200

print("original:", arr)
print("copy:", copy_arr)
print("view:", view_arr)

print("copy shares memory:", np.shares_memory(arr, copy_arr))
print("view shares memory:", np.shares_memory(arr, view_arr))


original: [  1 200   3   4]
copy: [100   2   3   4]
view: [  1 200   3   4]
copy shares memory: False
view shares memory: True


## 18. Sorting and searching

- `np.sort(arr)` → sorted values
- `np.argsort(arr)` → indices that would sort the array
- `np.argmax(arr)` → index of maximum
- `np.argmin(arr)` → index of minimum
- `np.unique(arr)` → unique sorted values

`argsort` is especially useful when you need the original positions.


In [16]:
arr = np.array([8, 3, 5, 1, 9])

print("sort:", np.sort(arr))
print("argsort:", np.argsort(arr))
print("max index:", np.argmax(arr))
print("min index:", np.argmin(arr))

x = np.array([1, 2, 2, 3, 4, 4, 5])
print("unique:", np.unique(x))


sort: [1 3 5 8 9]
argsort: [3 1 2 0 4]
max index: 4
min index: 3
unique: [1 2 3 4 5]


## 19. Random numbers

Modern NumPy recommends using a random `Generator` for new code.

```python
rng = np.random.default_rng(seed)
```

A seed makes results reproducible.

For integers:
```python
rng.integers(low, high, size=...)
```

Note: `high` is exclusive for `Generator.integers`.


In [ ]:
rng = np.random.default_rng(42)

random_ints = rng.integers(1, 51, size=(3, 4))
random_floats = rng.random((2, 3))

print(random_ints)
print(random_floats)


## 20. Correlation matrix

`np.corrcoef(X)` computes correlation coefficients.

If observations are rows and features/subjects are columns, use:

```python
np.corrcoef(X, rowvar=False)
```

or equivalently:

```python
np.corrcoef(X.T)
```

Correlation ranges from `-1` to `+1`:
- `+1` → perfect positive linear relationship
- `0` → no linear correlation
- `-1` → perfect negative linear relationship

**Correlation does not imply causation.**


In [17]:
data = np.array([
    [80, 75, 90],
    [85, 88, 92],
    [78, 80, 85],
    [90, 95, 98]
])

corr = np.corrcoef(data, rowvar=False)
print(corr)


[[1.         0.92493891 0.96541787]
 [0.92493891 1.         0.7983313 ]
 [0.96541787 0.7983313  1.        ]]


# 21. Mini EDA with NumPy

Suppose each row is:

`[age, subject_1_marks, subject_2_marks]`

Typical EDA questions:
- extract a column
- filter rows
- calculate averages
- find maximum scorer
- replace invalid/low values
- count values satisfying a condition
- inspect correlations


In [ ]:
data = np.array([
    [22, 85, 90],
    [19, 78, 88],
    [25, 92, 95],
    [18, 70, 75],
    [21, 88, 91]
])

ages = data[:, 0]
print("ages:", ages)

print("younger than 21:\n", data[data[:, 0] < 21])

print("average of columns:", np.mean(data, axis=0))
print("average age:", np.mean(data[:, 0]))

print("third column > 90:\n", data[data[:, 2] > 90])

marks_only = data[:, 1:]
total_scores = np.sum(marks_only, axis=1)
best_idx = np.argmax(total_scores)

print("totals:", total_scores)
print("best student index:", best_idx)
print("best student row:", data[best_idx])

print("correlation:\n", np.corrcoef(marks_only, rowvar=False))


## 22. Important correction from the original practice

A common normalization mistake is operator precedence.

Incorrect:
```python
arr - np.min(arr) / np.max(arr) - np.min(arr)
```

Correct:
```python
(arr - arr.min()) / (arr.max() - arr.min())
```

Always use parentheses when implementing formulas.


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)


# 23. Advanced NumPy concepts

## `keepdims=True`

Useful when you want reductions to retain dimensions for broadcasting.


In [21]:
data = np.array([[1, 2, 3],
                   [4, 5, 6]])

row_mean = data.mean(axis=1, keepdims=True)
print(row_mean)
print(np.mean(data))
print(data - row_mean)   # center each row


[[2.]
 [5.]]
3.5
[[-1.  0.  1.]
 [-1.  0.  1.]]


## `np.clip`

Restrict values to an interval.

```python
np.clip(arr, lower, upper)
```


In [22]:
arr = np.array([-10, 5, 20, 50, 100])
print(np.clip(arr, 0, 50))


[ 0  5 20 50 50]


## `np.any` and `np.all`

- `np.any(condition)` → at least one True
- `np.all(condition)` → every value True

These are useful for validation and row/column filtering.


In [23]:
arr = np.array([10, 20, 30])

print(np.any(arr > 25))
print(np.all(arr > 0))

matrix = np.array([[1, 2], [3, 4]])
print(np.any(matrix > 3, axis=1))
print(np.all(matrix > 0, axis=1))


True
True
[False  True]
[ True  True]


## `np.count_nonzero`

Count how many elements satisfy a condition.


In [24]:
arr = np.array([1, 0, 3, 0, 5])

print(np.count_nonzero(arr))
print(np.count_nonzero(arr > 2))


3
2


## `np.unique(..., return_counts=True)`

Extremely useful for frequency analysis.


In [25]:
arr = np.array([10, 20, 10, 30, 20, 10])

values, counts = np.unique(arr, return_counts=True)
print(values)
print(counts)


[10 20 30]
[3 2 1]


# 24. Hard Practice — Level 8/10

Try these **without looking at the solution**.

### Q1 — Row normalization
Given a matrix, normalize every row independently using min-max normalization.

### Q2 — Top-k indices
Given scores, return the indices of the top 3 values without sorting the entire array.

### Q3 — Second largest unique value
Find the second-largest **unique** value in a 1D array.

### Q4 — Conditional row filtering
Given a student matrix `[age, math, science, english]`, select students who:
- have average marks >= 80
- and no subject below 70.

### Q5 — Column standardization
Standardize every column independently so each feature has mean ≈ 0 and std ≈ 1.

### Q6 — Missing-value replacement
Replace `NaN` values in each column with that column's mean.

### Q7 — Duplicate rows
Find unique rows in a 2D array and their counts.

### Q8 — Pairwise distance
Given two matrices `A (n,d)` and `B (m,d)`, compute the Euclidean distance between every row of A and every row of B using broadcasting.

### Q9 — Running maximum
For `[3, 1, 5, 2, 7]`, produce `[3, 3, 5, 5, 7]`.

### Q10 — One-hot encoding
Given class labels `[0, 2, 1, 2]`, create a one-hot matrix for 3 classes using NumPy only.


In [26]:
# HARD Q1 — Row-wise min-max normalization

X = np.array([
    [10, 20, 30],
    [5, 10, 15],
    [100, 150, 200]
], dtype=float)

row_min = X.min(axis=1, keepdims=True)
row_max = X.max(axis=1, keepdims=True)

row_norm = (X - row_min) / (row_max - row_min)
print(row_norm)


[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]


In [ ]:
# HARD Q2 — Top 3 indices without full sorting

scores = np.array([91, 72, 99, 85, 96, 88])

top3 = np.argpartition(scores, -3)[-3:]
top3 = top3[np.argsort(scores[top3])[::-1]]

print("indices:", top3)
print("scores:", scores[top3])


In [ ]:
# HARD Q3 — Second-largest unique value

arr = np.array([10, 50, 20, 50, 30, 40, 40])

unique = np.unique(arr)

if unique.size < 2:
    print("No second-largest unique value")
else:
    print(unique[-2])


In [ ]:
# HARD Q4 — Student filtering

students = np.array([
    [20, 85, 90, 80],
    [21, 65, 95, 90],
    [19, 82, 81, 79],
    [22, 90, 88, 92]
])

marks = students[:, 1:]
avg = marks.mean(axis=1)

mask = (avg >= 80) & (marks.min(axis=1) >= 70)
print(students[mask])


In [ ]:
# HARD Q5 — Column standardization

X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
], dtype=float)

mu = X.mean(axis=0, keepdims=True)
sigma = X.std(axis=0, keepdims=True)

Z = (X - mu) / sigma

print(Z)
print("means:", Z.mean(axis=0))
print("stds:", Z.std(axis=0))


In [ ]:
# HARD Q6 — Fill NaNs with column means

X = np.array([
    [1.0, 10.0, np.nan],
    [2.0, np.nan, 30.0],
    [np.nan, 20.0, 40.0]
])

col_mean = np.nanmean(X, axis=0)
rows, cols = np.where(np.isnan(X))

X[rows, cols] = col_mean[cols]

print(X)


In [ ]:
# HARD Q7 — Unique rows + frequencies

X = np.array([
    [1, 2],
    [3, 4],
    [1, 2],
    [5, 6],
    [3, 4],
    [1, 2]
])

unique_rows, counts = np.unique(X, axis=0, return_counts=True)

print("unique rows:\n", unique_rows)
print("counts:", counts)


In [ ]:
# HARD Q8 — Pairwise Euclidean distances

A = np.array([
    [0, 0],
    [1, 1],
    [2, 2]
], dtype=float)

B = np.array([
    [0, 1],
    [3, 3]
], dtype=float)

# A[:, None, :] -> (n, 1, d)
# B[None, :, :] -> (1, m, d)
# Result -> (n, m, d), then reduce over d
distances = np.sqrt(np.sum((A[:, None, :] - B[None, :, :]) ** 2, axis=2))

print(distances)


In [ ]:
# HARD Q9 — Running maximum

arr = np.array([3, 1, 5, 2, 7])
print(np.maximum.accumulate(arr))


In [ ]:
# HARD Q10 — One-hot encoding

labels = np.array([0, 2, 1, 2])
num_classes = 3

one_hot = np.eye(num_classes, dtype=int)[labels]
print(one_hot)


# 25. Expert Challenge — 9/10

## Challenge A — Outlier detection with Z-score
Given a 2D dataset, calculate the Z-score for every feature and return rows containing at least one absolute Z-score > 2.

**Constraint:** NumPy only.

## Challenge B — Nearest neighbor
Given `X (n,d)` and one query vector `q (d,)`, find the index and distance of the closest row.

**Constraint:** no Python loop.

## Challenge C — Feature engineering
Given a matrix with columns `[age, income, experience]`:
1. calculate experience/age,
2. standardize income,
3. append both generated features to the original matrix.

## Challenge D — Per-group statistics
Given:
- `groups = [0, 1, 0, 1, 0]`
- `scores = [80, 90, 70, 100, 85]`

Calculate the mean score for each group using NumPy operations.

## Challenge E — Sliding-window maximum
Given a 1D array and window size `k`, calculate the maximum of every window.

First solve with a loop, then investigate a vectorized NumPy solution using `sliding_window_view`.


In [ ]:
# Expert Challenge A — solution

X = np.array([
    [10, 20, 30],
    [11, 21, 29],
    [10, 100, 31],
    [12, 22, 30]
], dtype=float)

z = (X - X.mean(axis=0)) / X.std(axis=0)

outlier_rows = X[np.any(np.abs(z) > 2, axis=1)]

print("Z-scores:\n", z)
print("outlier rows:\n", outlier_rows)


In [ ]:
# Expert Challenge B — nearest neighbor

X = np.array([
    [0, 0],
    [2, 2],
    [5, 5],
    [1, 1]
], dtype=float)

q = np.array([1.2, 1.1])

dist = np.linalg.norm(X - q, axis=1)
idx = np.argmin(dist)

print("nearest index:", idx)
print("nearest point:", X[idx])
print("distance:", dist[idx])


In [ ]:
# Expert Challenge C — feature engineering

X = np.array([
    [20, 50000, 1],
    [30, 80000, 6],
    [40, 100000, 12]
], dtype=float)

age = X[:, 0]
income = X[:, 1]
experience = X[:, 2]

exp_age = (experience / age)[:, None]
income_z = ((income - income.mean()) / income.std())[:, None]

features = np.column_stack((X, exp_age, income_z))

print(features)


In [ ]:
# Expert Challenge D — group means

groups = np.array([0, 1, 0, 1, 0])
scores = np.array([80, 90, 70, 100, 85])

for g in np.unique(groups):
    print(g, scores[groups == g].mean())


In [ ]:
# Expert Challenge E — sliding-window maximum
# NumPy >= 1.20

from numpy.lib.stride_tricks import sliding_window_view

arr = np.array([2, 1, 5, 3, 4, 6, 1])
k = 3

windows = sliding_window_view(arr, k)
result = windows.max(axis=1)

print(windows)
print(result)


# 26. Common mistakes

### Mistake 1 — `reshape()` without assignment
```python
arr.reshape(2, 3)
```
may return a reshaped array without changing `arr` itself.

Use:
```python
arr = arr.reshape(2, 3)
```

### Mistake 2 — Wrong boolean operators
Wrong:
```python
arr > 3 and arr < 8
```

Correct:
```python
(arr > 3) & (arr < 8)
```

### Mistake 3 — Forgetting parentheses
Wrong:
```python
arr > 3 & arr < 8
```

Correct:
```python
(arr > 3) & (arr < 8)
```

### Mistake 4 — Confusing `axis`
For a table:
- `axis=0` → each column
- `axis=1` → each row

### Mistake 5 — Assuming slices are always copies
NumPy views can share memory.

### Mistake 6 — Using Python loops unnecessarily
Prefer vectorization, broadcasting, reductions and boolean indexing.

### Mistake 7 — Division by zero in normalization
If `max == min`, min-max normalization has a zero denominator. Handle constant columns explicitly.

### Mistake 8 — Confusing `argmax` with `max`
- `max` → value
- `argmax` → index


# 27. Quick Revision Sheet

| Concept | Syntax |
|---|---|
| Create array | `np.array(...)` |
| Range | `np.arange(start, stop, step)` |
| Equal spacing | `np.linspace(start, stop, n)` |
| Zeros | `np.zeros(shape)` |
| Ones | `np.ones(shape)` |
| Identity | `np.eye(n)` |
| Shape | `arr.shape` |
| Elements | `arr.size` |
| Dimensions | `arr.ndim` |
| Reshape | `arr.reshape(...)` |
| Flatten copy | `arr.flatten()` |
| Ravel | `arr.ravel()` |
| Transpose | `arr.T` |
| Boolean filter | `arr[arr > x]` |
| Conditional | `np.where(...)` |
| Sum | `np.sum(arr)` |
| Mean | `np.mean(arr)` |
| Std | `np.std(arr)` |
| Min/max | `np.min`, `np.max` |
| Max index | `np.argmax` |
| Sort | `np.sort` |
| Sort indices | `np.argsort` |
| Unique | `np.unique` |
| Stack vertically | `np.vstack` |
| Stack horizontally | `np.hstack` |
| Concatenate | `np.concatenate` |
| Split | `np.split` |
| Copy | `arr.copy()` |
| View | `arr.view()` |
| Memory check | `np.shares_memory` |
| Correlation | `np.corrcoef` |
| Square root | `np.sqrt` |
| Absolute | `np.abs` |
| Clip | `np.clip` |
| Any true | `np.any` |
| All true | `np.all` |
| Count | `np.count_nonzero` |


# 28. Interview / Exam Questions

1. What is NumPy and why is it faster than Python lists for numerical work?
2. Explain `shape`, `size`, `ndim`, `dtype` and `itemsize`.
3. Difference between `arange` and `linspace`.
4. Difference between `reshape`, `resize` and flattening operations.
5. Explain broadcasting with a `(3,4)` matrix and `(4,)` vector.
6. Explain `axis=0` and `axis=1`.
7. Difference between `flatten()` and `ravel()`.
8. Difference between a NumPy copy and view.
9. What does `np.shares_memory()` test?
10. Difference between `max()` and `argmax()`.
11. Difference between `sort()` and `argsort()`.
12. How do boolean masks work?
13. Why are `&` and `|` used instead of `and` and `or`?
14. How would you replace all negative values with zero?
15. How would you normalize each column independently?
16. How would you find duplicate rows?
17. How would you calculate pairwise Euclidean distances without loops?
18. What is vectorization?
19. What is a ufunc?
20. Why can correlation be misleading?


# 29. Final Mastery Checklist

Before calling yourself strong in NumPy, you should be able to do these without help:

- [ ] Create 1D, 2D and 3D arrays
- [ ] Explain every major array attribute
- [ ] Use `arange`, `linspace`, `zeros`, `ones`, `eye`
- [ ] Index and slice 1D/2D/3D arrays
- [ ] Filter with multiple boolean conditions
- [ ] Replace values using masks and `where`
- [ ] Explain broadcasting
- [ ] Use vectorized arithmetic
- [ ] Calculate row/column statistics
- [ ] Standardize and normalize data
- [ ] Reshape, flatten and transpose
- [ ] Stack and split arrays
- [ ] Explain copy vs view
- [ ] Sort and obtain sorting indices
- [ ] Find unique values and frequencies
- [ ] Calculate correlation matrices
- [ ] Perform basic NumPy EDA
- [ ] Solve top-k, nearest-neighbor and pairwise-distance problems
- [ ] Use `keepdims`
- [ ] Handle NaNs
- [ ] Use broadcasting instead of unnecessary loops

**Target:** Solve the hard and expert problems from scratch, then explain *why* your solution works.
